def hangman_graphic(guesses):
		if guesses == 0:
			print ("              ")
			print ("              ")
			print ("              ")
			print ("              ")
			print ("              ")
			print ("              ")
		elif guesses == -1:
			print ("              ")
			print ("              ")
			print ("              ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
		elif guesses == -1:
			print ("              ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
		elif guesses == 1:
			print ("________      ")
			print ("|      |      ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
		elif guesses == 2:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|             ")
			print ("|             ")
			print ("|             ")
		elif guesses == 3:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|     /       ")
			print ("|             ")
			print ("|             ")
		elif guesses == 4:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|     /|      ")
			print ("|             ")
			print ("|             ")
		elif guesses == 5:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|     /|\     ")
			print ("|             ")
			print ("|             ")
		elif guesses == 6:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|     /|\     ")
			print ("|     /       ")
			print ("|             ")
		else:
			print ("________      ")
			print ("|      |      ")
			print ("|      0      ")
			print ("|     /|\     ")
			print ("|     / \     ")
			print ("|             ")
			print ("GAME OVER!")
